name: Release Please

on:
  push:
    branches:
      - main  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar nova release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: go

