name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Debug GitHub Token
        run: |
          echo "GH_TOKEN length: ${#GH_TOKEN}"
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "ERROR: GH_TOKEN is NOT set!"
            exit 1
          else
            echo "✅ GH_TOKEN is set."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install Goreleaser
        run: |
          curl -sL https://install.goreleaser.com | bash

      - name: Run Goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: goreleaser release --clean
