# name: Release Please

# on:
#   push:
#     branches:
#       - main  

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Code checkout
#         uses: actions/checkout@v4

#       - name: Generate Release PR
#         uses: google-github-actions/release-please-action@v4
#         with:
#           release-type: go

